### ISSUE TITLE
none of the Microsoft font files are legal to upload to github?

### ISSUE THREAD

**Issue by Pomax** [eugeneai/subook#1]
You've uploaded [a ton of Microsoft fonts](https://github.com/eugeneai/subook/tree/master/Microsoft) to github, none of which may legally be redistributed... so you're treading some pretty sketchy waters here. Are you sure you want to be doing this?

**Comment by eugeneai** [comment]
I'll correct the issue in a week.

2016-05-17 8:52 GMT+08:00 Mike Kamermans notifications@github.com:

**Comment by eugeneai** [comment]
Hi! 
I resolved the problem. None of the fonts are in the repo.

Thanks.
Evgeny
